#pragma output REGISTER_SP = 0x8181
#pragma output CLIB_MALLOC_HEAP_SIZE = 0x0000
#pragma output CRT_INTERRUPT_MODE_EXIT = 1
#pragma output CRT_ORG_CODE = 0x8184

#pragma output CRT_ORG_BANK_0 = 0x0C000
#pragma output CRT_ORG_BANK_1 = 0x1C000
#pragma output CRT_ORG_BANK_2 = 0x2C000
#pragma output CRT_ORG_BANK_3 = 0x3C000
#pragma output CRT_ORG_BANK_4 = 0x4C000
#pragma output CRT_ORG_BANK_5 = 0x5C000
#pragma output CRT_ORG_BANK_6 = 0x6C000
#pragma output CRT_ORG_BANK_7 = 0x7C000
