#!/bin/bash

function usage() {
	echo "Usage: $0 <sprite sheet> <mask sheet> [OPTIONS]"
	echo
	echo "OPTIONS:"
	echo "    -h           Display this text."
	echo "    -o <string>  Specify output asm file name."
	echo "    -f <int>     Number of frames contained in image files."
	echo "    -w <int>     Width of the sprite is bytes."
	echo
}

function c_to_asm() {
	inputFile=$1
	outputFile=$2

	echo "Converting to assembly..."
	zcc +zx -S $inputFile -o $outputFile

	echo "Formatting..."
	# Remove comments
	sed -i -e "/^\s*;/d" $outputFile
	# Remove blank lines
	sed -i -e "/^$/d" $outputFile
	# Remove lines containing unneeded directives
	sed -i -e "/^\s*[C_LINE|SECTION|MODULE|INCLUDE|GLOBAL]/d" $outputFile
	# Remove underscores
	sed -i -e "s/._/./" $outputFile

	asmstyle.pl $outputFile
	
	return 0
}

if [ $# -lt 2 ]
then
	usage
	exit 0
fi

argArray=( "$@" )

if [ ! -e $0 ]
then
	echo "$1 : file does not exist!"
	exit 1
fi

if [ ! -e $1 ]
then
	echo "$2 : file does not exist!"
	exit 1
fi

# Set default parameters
spriteSheet=${argArray[0]}
maskSheet=${argArray[1]}
outFile=${spriteSheet%.png}.inc
numFrames=8
spriteByteWidth=3

# Process command line starting at parameter #2
n=2
while [ "${argArray[n]}" != "" ]
do
	case "${argArray[n]}" in
	-o)
	   	n=$((n+1))
		outFile="${argArray[n]}"
		;;
	-f)
	   	n=$((n+1))
		numFrames="${argArray[n]}"
		;;
	-w)
	   	n=$((n+1))
		spriteByteWidth="${argArray[n]}"
		;;
	*)
		echo "Unknown parameter: ${argArray[n]}"
		usage
		exit 1
		;;
	esac
   n=$((n+1))
done

temp=`mktemp -d`
#temp=temp
#mkdir temp
echo "Creating $temp"

frame=0
ty=0
echo "/* Autogenerated by $0 */" > $temp/${spriteSheet%.png}.c 

while [ $frame -lt $numFrames ]
do
	echo "Creating frame $frame"
	
	tx=$((frame*spriteByteWidth*8))
	n=0
	while [ $n -lt $spriteByteWidth ]
	do
		convert $maskSheet -colorspace Gray -threshold 1% -crop 8x16+$tx+$ty $temp/${maskSheet%.png}$n.png
		convert $spriteSheet -colorspace Gray -threshold 1% -crop 8x16+$tx+$ty $temp/${spriteSheet%.png}$n.png
		tx=$((tx+=8))
		n=$((n+1))
	done

	convert \
		$temp/${maskSheet%.png}0.png $temp/${spriteSheet%.png}0.png \
		$temp/${maskSheet%.png}1.png $temp/${spriteSheet%.png}1.png \
		$temp/${maskSheet%.png}2.png $temp/${spriteSheet%.png}2.png \
		+append $temp/interlace.png

	convert -set comment "" $temp/interlace.png -negate -alpha off $temp/${spriteSheet%.png}$frame.h

	# Clean up the header file
	sed -i s/MagickImage/${spriteSheet%.png}$frame/ $temp/${spriteSheet%.png}$frame.h
	# Remove PNM header
	sed -i "s/^\s*0x50, 0x34, 0x0A,.*0x0A,.*0x0A, /    /" $temp/${spriteSheet%.png}$frame.h
	# Remove the static directive
	sed -i "s/static //" $temp/${spriteSheet%.png}$frame.h
	# Add the header to C source file
	echo "#include \"${spriteSheet%.png}$frame.h\"" >> $temp/${spriteSheet%.png}.c
	
	frame=$((frame+1))
done

c_to_asm "$temp/${spriteSheet%.png}.c" "$temp/$outFile"

cp -i $temp/$outFile ../src/sprite

echo "Removing $temp"
rm -rf $temp
