#!/bin/bash


if [ $# != 2 ]
then
	echo "Usage: $0 <input file> <output file>"
	exit 1
fi

mkdir -p $(dirname -- $2)

# Remove XML
cat $1 | sed -e "/^\s*</d" > $2.tmp

# Long winded way of changing tile 0 to tile 12
sed -i -e "s/,/, /g" -e "s/ 0,/ 12,/g" -e "s/^0,/12,/g" $2.tmp

# Replace comma with <SPACE>
sed -i -e "s/,/ /g" $2.tmp

echo "; Autogenerated by $0" > $2
while read line
do
	printf "        db      " >> $2
	for num in $line
	do
		num=${num%$'\r'}
		num=$(($num-1))
		printf "0x%02x, " $num >> $2
	done
	printf "\n" >> $2
done < $2.tmp


# Remove comma from end of lines
sed -i "s/, $//g" $2

rm -f $2.tmp

