tile0:
        defb    0
        defb    0
        defb    1
        defb    3
        defb    3
        defb    0
        defb    62
        defb    30
tile1:
        defb    0
        defb    0
        defb    213
        defb    183
        defb    246
        defb    0
        defb    147
        defb    41
tile2:
        defb    0
        defb    0
        defb    128
        defb    64
        defb    128
        defb    0
        defb    94
        defb    124
tile3:
        defb    0
        defb    0
        defb    130
        defb    66
        defb    103
        defb    231
        defb    66
        defb    0
tile4:
        defb    198
        defb    198
        defb    190
        defb    246
        defb    108
        defb    96
        defb    108
        defb    108
tile5:
        defb    32
        defb    52
        defb    84
        defb    87
        defb    85
        defb    219
        defb    178
        defb    165
tile6:
        defb    4
        defb    44
        defb    42
        defb    234
        defb    170
        defb    219
        defb    77
        defb    165
tile7:
        defb    2
        defb    5
        defb    15
        defb    8
        defb    19
        defb    24
        defb    12
        defb    1
tile8:
        defb    192
        defb    144
        defb    120
        defb    228
        defb    94
        defb    176
        defb    77
        defb    46
tile9:
        defb    1
        defb    4
        defb    15
        defb    19
        defb    61
        defb    6
        defb    217
        defb    186
tile10:
        defb    160
        defb    208
        defb    120
        defb    136
        defb    100
        defb    140
        defb    24
        defb    64
tile11:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile12:
        defb    0
        defb    0
        defb    130
        defb    66
        defb    103
        defb    231
        defb    66
        defb    0
tile13:
        defb    0
        defb    0
        defb    66
        defb    71
        defb    103
        defb    231
        defb    66
        defb    0
tile14:
        defb    0
        defb    0
        defb    36
        defb    66
        defb    199
        defb    231
        defb    66
        defb    0
tile15:
        defb    0
        defb    0
        defb    65
        defb    99
        defb    231
        defb    231
        defb    66
        defb    0
tile16:
        defb    62
        defb    0
        defb    249
        defb    122
        defb    178
        defb    4
        defb    116
        defb    52
tile17:
        defb    68
        defb    130
        defb    69
        defb    40
        defb    56
        defb    16
        defb    16
        defb    16
tile18:
        defb    122
        defb    0
        defb    30
        defb    157
        defb    138
        defb    64
        defb    76
        defb    72
tile19:
        defb    66
        defb    0
        defb    231
        defb    66
        defb    24
        defb    66
        defb    66
        defb    0
tile20:
        defb    108
        defb    96
        defb    108
        defb    118
        defb    182
        defb    198
        defb    198
        defb    198
tile21:
        defb    200
        defb    204
        defb    151
        defb    186
        defb    48
        defb    17
        defb    24
        defb    112
tile22:
        defb    35
        defb    35
        defb    105
        defb    93
        defb    204
        defb    76
        defb    24
        defb    14
tile23:
        defb    4
        defb    0
        defb    98
        defb    40
        defb    26
        defb    13
        defb    0
        defb    0
tile24:
        defb    7
        defb    186
        defb    75
        defb    79
        defb    173
        defb    17
        defb    13
        defb    2
tile25:
        defb    112
        defb    46
        defb    233
        defb    249
        defb    218
        defb    196
        defb    216
        defb    160
tile26:
        defb    16
        defb    128
        defb    35
        defb    10
        defb    172
        defb    88
        defb    0
        defb    0
tile27:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile28:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile29:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile30:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile31:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile32:
        defb    84
        defb    7
        defb    116
        defb    180
        defb    84
        defb    4
        defb    52
        defb    23
tile33:
        defb    16
        defb    255
        defb    16
        defb    16
        defb    16
        defb    16
        defb    16
        defb    255
tile34:
        defb    76
        defb    192
        defb    79
        defb    78
        defb    77
        defb    64
        defb    78
        defb    204
tile35:
        defb    3
        defb    1
        defb    3
        defb    0
        defb    15
        defb    7
        defb    11
        defb    0
tile36:
        defb    224
        defb    192
        defb    160
        defb    0
        defb    232
        defb    208
        defb    168
        defb    0
tile37:
        defb    27
        defb    55
        defb    111
        defb    111
        defb    105
        defb    106
        defb    105
        defb    106
tile38:
        defb    248
        defb    252
        defb    254
        defb    254
        defb    166
        defb    170
        defb    166
        defb    174
tile39:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile40:
        defb    6
        defb    4
        defb    2
        defb    4
        defb    2
        defb    2
        defb    1
        defb    0
tile41:
        defb    176
        defb    144
        defb    32
        defb    144
        defb    32
        defb    32
        defb    64
        defb    0
tile42:
        defb    0
        defb    108
        defb    222
        defb    190
        defb    92
        defb    56
        defb    16
        defb    0
tile43:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile44:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile45:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile46:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile47:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile48:
        defb    52
        defb    4
        defb    244
        defb    116
        defb    180
        defb    7
        defb    112
        defb    55
tile49:
        defb    16
        defb    16
        defb    16
        defb    16
        defb    16
        defb    255
        defb    0
        defb    255
tile50:
        defb    74
        defb    64
        defb    78
        defb    77
        defb    74
        defb    192
        defb    12
        defb    72
tile51:
        defb    7
        defb    3
        defb    5
        defb    0
        defb    23
        defb    11
        defb    21
        defb    0
tile52:
        defb    192
        defb    128
        defb    192
        defb    0
        defb    240
        defb    224
        defb    208
        defb    0
tile53:
        defb    111
        defb    111
        defb    111
        defb    111
        defb    111
        defb    111
        defb    128
        defb    111
tile54:
        defb    254
        defb    254
        defb    254
        defb    254
        defb    254
        defb    254
        defb    1
        defb    254
tile55:
        defb    0
        defb    31
        defb    0
        defb    54
        defb    45
        defb    0
        defb    127
        defb    0
tile56:
        defb    0
        defb    200
        defb    0
        defb    132
        defb    196
        defb    0
        defb    226
        defb    0
tile57:
        defb    198
        defb    198
        defb    198
        defb    190
        defb    124
        defb    0
        defb    0
        defb    0
tile58:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile59:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile60:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile61:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile62:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile63:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile64:
        defb    87
        defb    0
        defb    112
        defb    187
        defb    90
        defb    0
        defb    0
        defb    0
tile65:
        defb    250
        defb    0
        defb    0
        defb    78
        defb    205
        defb    0
        defb    0
        defb    0
tile66:
        defb    140
        defb    0
        defb    63
        defb    158
        defb    61
        defb    0
        defb    0
        defb    0
tile67:
        defb    4
        defb    84
        defb    48
        defb    16
        defb    48
        defb    84
        defb    68
        defb    4
tile68:
        defb    64
        defb    84
        defb    48
        defb    16
        defb    48
        defb    84
        defb    68
        defb    64
tile69:
        defb    1
        defb    3
        defb    6
        defb    15
        defb    15
        defb    31
        defb    19
        defb    33
tile70:
        defb    128
        defb    192
        defb    224
        defb    144
        defb    144
        defb    248
        defb    248
        defb    252
tile71:
        defb    93
        defb    0
        defb    127
        defb    0
        defb    45
        defb    54
        defb    0
        defb    31
tile72:
        defb    194
        defb    0
        defb    226
        defb    0
        defb    196
        defb    132
        defb    0
        defb    200
tile73:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile74:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile75:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile76:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile77:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile78:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile79:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile80:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    44
        defb    0
tile81:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    66
        defb    118
        defb    60
        defb    0
tile82:
        defb    0
        defb    0
        defb    0
        defb    66
        defb    122
        defb    118
        defb    60
        defb    0
tile83:
        defb    0
        defb    36
        defb    60
        defb    94
        defb    122
        defb    118
        defb    60
        defb    0
tile84:
        defb    24
        defb    52
        defb    60
        defb    94
        defb    122
        defb    118
        defb    60
        defb    0
tile85:
        defb    33
        defb    51
        defb    63
        defb    23
        defb    28
        defb    12
        defb    3
        defb    0
tile86:
        defb    204
        defb    132
        defb    132
        defb    200
        defb    248
        defb    240
        defb    192
        defb    0
tile87:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile88:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile89:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile90:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile91:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile92:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile93:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile94:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile95:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile96:
        defb    56
        defb    68
        defb    186
        defb    186
        defb    186
        defb    68
        defb    56
        defb    0
tile97:
        defb    56
        defb    76
        defb    84
        defb    116
        defb    84
        defb    76
        defb    56
        defb    0
tile98:
        defb    16
        defb    56
        defb    56
        defb    56
        defb    56
        defb    56
        defb    16
        defb    0
tile99:
        defb    56
        defb    100
        defb    84
        defb    92
        defb    84
        defb    100
        defb    56
        defb    0
tile100:
        defb    0
        defb    127
        defb    61
        defb    90
        defb    0
        defb    0
        defb    15
        defb    31
tile101:
        defb    0
        defb    178
        defb    66
        defb    162
        defb    0
        defb    0
        defb    128
        defb    196
tile102:
        defb    63
        defb    127
        defb    225
        defb    192
        defb    204
        defb    204
        defb    193
        defb    227
tile103:
        defb    7
        defb    143
        defb    220
        defb    185
        defb    115
        defb    232
        defb    223
        defb    143
tile104:
        defb    252
        defb    254
        defb    7
        defb    242
        defb    249
        defb    3
        defb    255
        defb    254
tile105:
        defb    31
        defb    63
        defb    112
        defb    231
        defb    207
        defb    160
        defb    127
        defb    63
tile106:
        defb    224
        defb    241
        defb    59
        defb    151
        defb    206
        defb    29
        defb    251
        defb    241
tile107:
        defb    252
        defb    254
        defb    135
        defb    3
        defb    51
        defb    51
        defb    131
        defb    199
tile108:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile109:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile110:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile111:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile112:
        defb    0
        defb    191
        defb    0
        defb    86
        defb    111
        defb    0
        defb    44
        defb    88
tile113:
        defb    0
        defb    255
        defb    0
        defb    125
        defb    131
        defb    125
        defb    0
        defb    0
tile114:
        defb    0
        defb    255
        defb    0
        defb    190
        defb    193
        defb    190
        defb    0
        defb    0
tile115:
        defb    0
        defb    253
        defb    0
        defb    106
        defb    246
        defb    0
        defb    52
        defb    26
tile116:
        defb    47
        defb    19
        defb    44
        defb    27
        defb    60
        defb    31
        defb    63
        defb    31
tile117:
        defb    132
        defb    64
        defb    132
        defb    0
        defb    196
        defb    0
        defb    132
        defb    196
tile118:
        defb    219
        defb    203
        defb    227
        defb    119
        defb    58
        defb    28
        defb    46
        defb    119
tile119:
        defb    4
        defb    9
        defb    24
        defb    29
        defb    62
        defb    43
        defb    33
        defb    0
tile120:
        defb    16
        defb    72
        defb    140
        defb    220
        defb    190
        defb    106
        defb    194
        defb    128
tile121:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile122:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile123:
        defb    238
        defb    92
        defb    56
        defb    116
        defb    238
        defb    199
        defb    211
        defb    219
tile124:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile125:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile126:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile127:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile128:
        defb    80
        defb    48
        defb    48
        defb    8
        defb    24
        defb    8
        defb    16
        defb    48
tile129:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile130:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile131:
        defb    10
        defb    12
        defb    12
        defb    16
        defb    24
        defb    16
        defb    8
        defb    12
tile132:
        defb    47
        defb    19
        defb    44
        defb    27
        defb    0
        defb    127
        defb    61
        defb    90
tile133:
        defb    132
        defb    64
        defb    132
        defb    4
        defb    0
        defb    178
        defb    66
        defb    162
tile134:
        defb    227
        defb    193
        defb    204
        defb    204
        defb    192
        defb    225
        defb    127
        defb    63
tile135:
        defb    143
        defb    223
        defb    232
        defb    115
        defb    185
        defb    220
        defb    143
        defb    7
tile136:
        defb    254
        defb    255
        defb    3
        defb    249
        defb    242
        defb    7
        defb    254
        defb    252
tile137:
        defb    63
        defb    127
        defb    160
        defb    207
        defb    231
        defb    112
        defb    63
        defb    31
tile138:
        defb    241
        defb    251
        defb    29
        defb    206
        defb    151
        defb    59
        defb    241
        defb    224
tile139:
        defb    199
        defb    131
        defb    51
        defb    51
        defb    3
        defb    135
        defb    254
        defb    252
tile140:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile141:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile142:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile143:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile144:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile145:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile146:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile147:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile148:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile149:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile150:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile151:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile152:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile153:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile154:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile155:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile156:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile157:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile158:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile159:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile160:
        defb    28
        defb    44
        defb    52
        defb    56
        defb    28
        defb    44
        defb    52
        defb    56
tile161:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile162:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile163:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile164:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile165:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile166:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile167:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
tile168:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
tile169:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile170:
        defb    0
        defb    127
        defb    127
        defb    127
        defb    111
        defb    127
        defb    54
        defb    64
tile171:
        defb    0
        defb    254
        defb    252
        defb    190
        defb    236
        defb    122
        defb    208
        defb    0
tile172:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile173:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile174:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile175:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile176:
        defb    28
        defb    44
        defb    52
        defb    56
        defb    28
        defb    44
        defb    52
        defb    56
tile177:
        defb    28
        defb    44
        defb    0
        defb    122
        defb    94
        defb    126
        defb    0
        defb    60
tile178:
        defb    0
        defb    124
        defb    194
        defb    146
        defb    138
        defb    182
        defb    162
        defb    84
tile179:
        defb    0
        defb    127
        defb    61
        defb    90
        defb    0
        defb    0
        defb    15
        defb    31
tile180:
        defb    0
        defb    178
        defb    66
        defb    162
        defb    0
        defb    0
        defb    128
        defb    196
tile181:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
tile182:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
tile183:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
tile184:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
tile185:
        defb    205
        defb    187
        defb    221
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile186:
        defb    0
        defb    127
        defb    127
        defb    127
        defb    111
        defb    127
        defb    54
        defb    64
tile187:
        defb    0
        defb    254
        defb    252
        defb    190
        defb    236
        defb    122
        defb    208
        defb    0
tile188:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile189:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile190:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile191:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile192:
        defb    0
        defb    127
        defb    127
        defb    127
        defb    111
        defb    127
        defb    54
        defb    64
tile193:
        defb    0
        defb    254
        defb    252
        defb    190
        defb    236
        defb    122
        defb    208
        defb    0
tile194:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
tile195:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
tile196:
        defb    0
        defb    124
        defb    194
        defb    146
        defb    138
        defb    182
        defb    162
        defb    84
tile197:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    149
        defb    175
        defb    215
        defb    159
tile198:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    198
        defb    234
        defb    182
        defb    250
tile199:
        defb    205
        defb    187
        defb    221
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile200:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile201:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile202:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile203:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile204:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile205:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile206:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile207:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile208:
        defb    0
        defb    127
        defb    127
        defb    127
        defb    111
        defb    127
        defb    54
        defb    64
tile209:
        defb    0
        defb    254
        defb    252
        defb    190
        defb    236
        defb    122
        defb    208
        defb    0
tile210:
        defb    0
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
tile211:
        defb    0
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
tile212:
        defb    0
        defb    124
        defb    194
        defb    146
        defb    138
        defb    182
        defb    162
        defb    84
tile213:
        defb    191
        defb    222
        defb    191
        defb    223
        defb    255
        defb    175
        defb    149
        defb    90
tile214:
        defb    242
        defb    250
        defb    218
        defb    246
        defb    234
        defb    114
        defb    162
        defb    84
tile215:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile216:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile217:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile218:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile219:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile220:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile221:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile222:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile223:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile224:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile225:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile226:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile227:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile228:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile229:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile230:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile231:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile232:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile233:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile234:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile235:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile236:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile237:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile238:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile239:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile240:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile241:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile242:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile243:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile244:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile245:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile246:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile247:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile248:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile249:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile250:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile251:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile252:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile253:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile254:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
tile255:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
