#!/bin/bash

if [ $# != 2 ]
then
	echo "Usage: csv2asm.sh <input file> <output file>"
	exit
fi

# Convert -1 to 11
sed -i "s/-1/11/g" ${1}
# Replace , with <SPACE>
sed -i "s/,/ /g" ${1}
echo "; Autogenerated from ${1}" > ${2}
while read line
do
	printf "        db      " >> ${2}
	for num in $line
	do
		num=${num%$'\r'}
		printf "0x%02x, " $num >> ${2}
	done
	printf "\n" >> ${2}
done < ${1}

sed -i "s/, $//g" ${2}

