#!/bin/bash
set -u


if [ $# = 0 ]
then
	echo "Usage: $0 <tile sheet png>"
	exit 0
fi

if [ ! -e $1 ]
then
	echo "$1 does not exist!"
	exit 1
fi

tileSheet=$1
# Tile height in pixels
tileHeight=16
# Tile width in pixels
tileWidth=48
outDir=sprites
# Width of sprite sheet in tiles
width=8
# Height of sprite sheet in tiles
height=1

mkdir -p ${outDir}

tile=0
y=0
x=0
tileSet=${outDir}/${tileSheet%.png}.c

echo "/* Autogenerated using $0 */" > $tileSet

while [ $y -lt $height ]
do
	while [ $x -lt $width ]
	do
		let tx=$x*$tileWidth
		let ty=$y*$tileHeight
		
		echo "Tile X=$tx,Y=$ty -> ${outDir}/${tileSheet%.png}${tile}.h"
		
		convert ${tileSheet} -colorspace Gray -threshold 1% -crop ${tileWidth}x${tileHeight}+$tx+$ty ${outDir}/${tileSheet%.png}${tile}.png
		convert ${outDir}/${tileSheet%.png}${tile}.png -negate -alpha off ${outDir}/${tileSheet%.png}${tile}.h
		sed -i s/MagickImage/${tileSheet%.png}${tile}/ ${outDir}/${tileSheet%.png}${tile}.h
		sed -i "s/^\s*0x50, 0x34, 0x0A, 0x.., 0x.., 0x20, 0x.., 0x.., 0x0A, /    /" ${outDir}/${tileSheet%.png}${tile}.h
		sed -i "s/static //" ${outDir}/${tileSheet%.png}${tile}.h
		echo "#include \"${tileSheet%.png}${tile}.h\"" >> $tileSet
		let tile=$tile+1
		let x=$x+1
	done
	let y=$y+1
done

echo "Converting to assembly..."
zcc +zx -S ${tileSet} -o ${outDir}/${tileSheet%.png}.inc

echo "Formatting..."
# Remove comments
sed -i -e "/^\s*;/d" ${outDir}/${tileSheet%.png}.inc
# Remove blank lines
sed -i -e "/^$/d" ${outDir}/${tileSheet%.png}.inc
# Remove lines containing unneeded directives
sed -i -e "/^\s*[C_LINE|SECTION|MODULE|INCLUDE|GLOBAL]/d" ${outDir}/${tileSheet%.png}.inc
# Remove underscores
#sed -i -e "s/._/./" ${outDir}/tiles.inc

asmstyle.pl ${outDir}/${tileSheet%.png}.inc

cp -i ${outDir}/${tileSheet%.png}.inc ../src/sprite
echo "Done"
