_tile0:
        defb    0
        defb    0
        defb    1
        defb    3
        defb    3
        defb    0
        defb    62
        defb    30
_tile1:
        defb    0
        defb    0
        defb    213
        defb    183
        defb    246
        defb    0
        defb    147
        defb    41
_tile2:
        defb    0
        defb    0
        defb    128
        defb    64
        defb    128
        defb    0
        defb    94
        defb    124
_tile3:
        defb    0
        defb    0
        defb    130
        defb    66
        defb    103
        defb    231
        defb    66
        defb    0
_tile4:
        defb    99
        defb    99
        defb    95
        defb    123
        defb    54
        defb    48
        defb    54
        defb    54
_tile5:
        defb    32
        defb    52
        defb    84
        defb    87
        defb    85
        defb    219
        defb    178
        defb    165
_tile6:
        defb    4
        defb    44
        defb    42
        defb    234
        defb    170
        defb    219
        defb    77
        defb    165
_tile7:
        defb    2
        defb    5
        defb    15
        defb    8
        defb    19
        defb    24
        defb    12
        defb    1
_tile8:
        defb    192
        defb    144
        defb    120
        defb    228
        defb    94
        defb    176
        defb    77
        defb    46
_tile9:
        defb    1
        defb    4
        defb    15
        defb    19
        defb    61
        defb    6
        defb    217
        defb    186
_tile10:
        defb    160
        defb    208
        defb    120
        defb    136
        defb    100
        defb    140
        defb    24
        defb    64
_tile11:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile12:
        defb    62
        defb    0
        defb    249
        defb    122
        defb    178
        defb    4
        defb    116
        defb    52
_tile13:
        defb    68
        defb    130
        defb    69
        defb    40
        defb    56
        defb    16
        defb    16
        defb    16
_tile14:
        defb    122
        defb    0
        defb    30
        defb    157
        defb    138
        defb    64
        defb    76
        defb    72
_tile15:
        defb    66
        defb    0
        defb    231
        defb    66
        defb    24
        defb    66
        defb    0
        defb    0
_tile16:
        defb    54
        defb    48
        defb    54
        defb    59
        defb    91
        defb    99
        defb    99
        defb    99
_tile17:
        defb    200
        defb    204
        defb    151
        defb    186
        defb    48
        defb    17
        defb    24
        defb    112
_tile18:
        defb    35
        defb    35
        defb    105
        defb    93
        defb    204
        defb    76
        defb    24
        defb    14
_tile19:
        defb    4
        defb    0
        defb    98
        defb    40
        defb    26
        defb    13
        defb    0
        defb    0
_tile20:
        defb    7
        defb    186
        defb    75
        defb    79
        defb    173
        defb    17
        defb    13
        defb    2
_tile21:
        defb    112
        defb    46
        defb    233
        defb    249
        defb    218
        defb    196
        defb    216
        defb    160
_tile22:
        defb    16
        defb    128
        defb    35
        defb    10
        defb    172
        defb    88
        defb    0
        defb    0
_tile23:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile24:
        defb    84
        defb    7
        defb    116
        defb    180
        defb    84
        defb    4
        defb    52
        defb    23
_tile25:
        defb    16
        defb    255
        defb    16
        defb    16
        defb    16
        defb    16
        defb    16
        defb    255
_tile26:
        defb    76
        defb    192
        defb    79
        defb    78
        defb    77
        defb    64
        defb    78
        defb    204
_tile27:
        defb    3
        defb    1
        defb    3
        defb    0
        defb    15
        defb    7
        defb    11
        defb    0
_tile28:
        defb    224
        defb    192
        defb    160
        defb    0
        defb    232
        defb    208
        defb    168
        defb    0
_tile29:
        defb    0
        defb    7
        defb    15
        defb    17
        defb    62
        defb    43
        defb    42
        defb    42
_tile30:
        defb    0
        defb    212
        defb    238
        defb    246
        defb    118
        defb    178
        defb    210
        defb    160
_tile31:
        defb    24
        defb    52
        defb    60
        defb    94
        defb    122
        defb    118
        defb    60
        defb    0
_tile32:
        defb    6
        defb    4
        defb    2
        defb    4
        defb    2
        defb    2
        defb    1
        defb    0
_tile33:
        defb    176
        defb    144
        defb    32
        defb    144
        defb    32
        defb    32
        defb    64
        defb    0
_tile34:
        defb    0
        defb    108
        defb    222
        defb    190
        defb    92
        defb    56
        defb    16
        defb    0
_tile35:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile36:
        defb    52
        defb    4
        defb    244
        defb    116
        defb    180
        defb    7
        defb    112
        defb    55
_tile37:
        defb    16
        defb    16
        defb    16
        defb    16
        defb    16
        defb    255
        defb    0
        defb    255
_tile38:
        defb    74
        defb    64
        defb    78
        defb    77
        defb    74
        defb    192
        defb    12
        defb    72
_tile39:
        defb    7
        defb    3
        defb    5
        defb    0
        defb    23
        defb    11
        defb    21
        defb    0
_tile40:
        defb    192
        defb    128
        defb    192
        defb    0
        defb    240
        defb    224
        defb    208
        defb    0
_tile41:
        defb    27
        defb    12
        defb    0
        defb    14
        defb    12
        defb    0
        defb    1
        defb    7
_tile42:
        defb    72
        defb    180
        defb    118
        defb    230
        defb    22
        defb    166
        defb    18
        defb    56
_tile43:
        defb    0
        defb    31
        defb    0
        defb    54
        defb    45
        defb    0
        defb    127
        defb    0
_tile44:
        defb    0
        defb    200
        defb    0
        defb    132
        defb    196
        defb    0
        defb    226
        defb    0
_tile45:
        defb    99
        defb    99
        defb    99
        defb    95
        defb    62
        defb    0
        defb    0
        defb    0
_tile46:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile47:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile48:
        defb    87
        defb    0
        defb    112
        defb    187
        defb    90
        defb    0
        defb    0
        defb    0
_tile49:
        defb    250
        defb    0
        defb    0
        defb    78
        defb    205
        defb    0
        defb    0
        defb    0
_tile50:
        defb    140
        defb    0
        defb    63
        defb    158
        defb    61
        defb    0
        defb    0
        defb    0
_tile51:
        defb    4
        defb    84
        defb    48
        defb    16
        defb    48
        defb    84
        defb    68
        defb    4
_tile52:
        defb    64
        defb    84
        defb    48
        defb    16
        defb    48
        defb    84
        defb    68
        defb    64
_tile53:
        defb    1
        defb    3
        defb    6
        defb    15
        defb    15
        defb    31
        defb    19
        defb    33
_tile54:
        defb    128
        defb    192
        defb    224
        defb    144
        defb    144
        defb    248
        defb    248
        defb    252
_tile55:
        defb    93
        defb    0
        defb    127
        defb    0
        defb    45
        defb    54
        defb    0
        defb    31
_tile56:
        defb    194
        defb    0
        defb    226
        defb    0
        defb    196
        defb    132
        defb    0
        defb    200
_tile57:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile58:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile59:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile60:
        defb    24
        defb    36
        defb    36
        defb    66
        defb    66
        defb    66
        defb    60
        defb    0
_tile61:
        defb    24
        defb    36
        defb    36
        defb    66
        defb    66
        defb    118
        defb    60
        defb    0
_tile62:
        defb    24
        defb    36
        defb    36
        defb    66
        defb    122
        defb    118
        defb    60
        defb    0
_tile63:
        defb    24
        defb    36
        defb    36
        defb    94
        defb    122
        defb    118
        defb    60
        defb    0
_tile64:
        defb    24
        defb    36
        defb    60
        defb    94
        defb    122
        defb    118
        defb    60
        defb    0
_tile65:
        defb    33
        defb    51
        defb    63
        defb    23
        defb    28
        defb    12
        defb    3
        defb    0
_tile66:
        defb    204
        defb    132
        defb    132
        defb    200
        defb    248
        defb    240
        defb    192
        defb    0
_tile67:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile68:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile69:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile70:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile71:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile72:
        defb    56
        defb    68
        defb    186
        defb    186
        defb    186
        defb    68
        defb    56
        defb    0
_tile73:
        defb    56
        defb    76
        defb    84
        defb    116
        defb    84
        defb    76
        defb    56
        defb    0
_tile74:
        defb    16
        defb    56
        defb    56
        defb    56
        defb    56
        defb    56
        defb    16
        defb    0
_tile75:
        defb    56
        defb    100
        defb    84
        defb    92
        defb    84
        defb    100
        defb    56
        defb    0
_tile76:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile77:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile78:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile79:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile80:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile81:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile82:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile83:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile84:
        defb    191
        defb    0
        defb    86
        defb    111
        defb    0
        defb    44
        defb    88
        defb    80
_tile85:
        defb    255
        defb    0
        defb    125
        defb    131
        defb    125
        defb    0
        defb    0
        defb    0
_tile86:
        defb    255
        defb    0
        defb    190
        defb    193
        defb    190
        defb    0
        defb    0
        defb    0
_tile87:
        defb    253
        defb    0
        defb    106
        defb    246
        defb    0
        defb    52
        defb    26
        defb    10
_tile88:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile89:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile90:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile91:
        defb    0
        defb    127
        defb    61
        defb    90
        defb    0
        defb    0
        defb    15
        defb    31
_tile92:
        defb    0
        defb    178
        defb    66
        defb    162
        defb    0
        defb    0
        defb    128
        defb    196
_tile93:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile94:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile95:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile96:
        defb    48
        defb    48
        defb    8
        defb    24
        defb    8
        defb    16
        defb    48
        defb    0
_tile97:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile98:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile99:
        defb    12
        defb    12
        defb    16
        defb    24
        defb    16
        defb    8
        defb    12
        defb    0
_tile100:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile101:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile102:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile103:
        defb    47
        defb    19
        defb    44
        defb    27
        defb    60
        defb    31
        defb    63
        defb    31
_tile104:
        defb    132
        defb    64
        defb    132
        defb    0
        defb    196
        defb    0
        defb    132
        defb    196
_tile105:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile106:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile107:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile108:
        defb    63
        defb    127
        defb    225
        defb    192
        defb    204
        defb    204
        defb    193
        defb    227
_tile109:
        defb    7
        defb    143
        defb    220
        defb    185
        defb    115
        defb    232
        defb    223
        defb    143
_tile110:
        defb    252
        defb    254
        defb    7
        defb    242
        defb    249
        defb    3
        defb    255
        defb    254
_tile111:
        defb    31
        defb    63
        defb    112
        defb    231
        defb    207
        defb    160
        defb    127
        defb    63
_tile112:
        defb    224
        defb    241
        defb    59
        defb    151
        defb    206
        defb    29
        defb    251
        defb    241
_tile113:
        defb    252
        defb    254
        defb    135
        defb    3
        defb    51
        defb    51
        defb    131
        defb    199
_tile114:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile115:
        defb    47
        defb    19
        defb    44
        defb    27
        defb    0
        defb    127
        defb    61
        defb    90
_tile116:
        defb    132
        defb    64
        defb    132
        defb    4
        defb    0
        defb    178
        defb    66
        defb    162
_tile117:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile118:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile119:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile120:
        defb    219
        defb    203
        defb    227
        defb    119
        defb    58
        defb    28
        defb    46
        defb    119
_tile121:
        defb    4
        defb    9
        defb    24
        defb    29
        defb    62
        defb    43
        defb    33
        defb    0
_tile122:
        defb    16
        defb    72
        defb    140
        defb    220
        defb    190
        defb    106
        defb    194
        defb    128
_tile123:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile124:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile125:
        defb    238
        defb    92
        defb    56
        defb    116
        defb    238
        defb    199
        defb    211
        defb    219
_tile126:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile127:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile128:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile129:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile130:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile131:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile132:
        defb    227
        defb    193
        defb    204
        defb    204
        defb    192
        defb    225
        defb    127
        defb    63
_tile133:
        defb    143
        defb    223
        defb    232
        defb    115
        defb    185
        defb    220
        defb    143
        defb    7
_tile134:
        defb    254
        defb    255
        defb    3
        defb    249
        defb    242
        defb    7
        defb    254
        defb    252
_tile135:
        defb    63
        defb    127
        defb    160
        defb    207
        defb    231
        defb    112
        defb    63
        defb    31
_tile136:
        defb    241
        defb    251
        defb    29
        defb    206
        defb    151
        defb    59
        defb    241
        defb    224
_tile137:
        defb    199
        defb    131
        defb    51
        defb    51
        defb    3
        defb    135
        defb    254
        defb    252
_tile138:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile139:
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
        defb    0
_tile140:
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
        defb    0
_tile141:
        defb    205
        defb    187
        defb    221
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile142:
        defb    255
        defb    255
        defb    255
        defb    223
        defb    254
        defb    109
        defb    128
        defb    0
_tile143:
        defb    252
        defb    248
        defb    124
        defb    216
        defb    244
        defb    160
        defb    0
        defb    0
_tile144:
        defb    255
        defb    255
        defb    255
        defb    223
        defb    254
        defb    109
        defb    128
        defb    0
_tile145:
        defb    252
        defb    248
        defb    124
        defb    216
        defb    244
        defb    160
        defb    0
        defb    0
_tile146:
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
        defb    0
_tile147:
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
        defb    0
_tile148:
        defb    124
        defb    194
        defb    146
        defb    138
        defb    182
        defb    162
        defb    84
        defb    0
_tile149:
        defb    127
        defb    192
        defb    138
        defb    149
        defb    175
        defb    215
        defb    159
        defb    191
_tile150:
        defb    252
        defb    2
        defb    162
        defb    198
        defb    234
        defb    182
        defb    250
        defb    242
_tile151:
        defb    205
        defb    187
        defb    221
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile152:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile153:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile154:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile155:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile156:
        defb    255
        defb    255
        defb    255
        defb    223
        defb    254
        defb    109
        defb    128
        defb    0
_tile157:
        defb    252
        defb    248
        defb    124
        defb    216
        defb    244
        defb    160
        defb    0
        defb    0
_tile158:
        defb    127
        defb    192
        defb    138
        defb    151
        defb    175
        defb    149
        defb    90
        defb    0
_tile159:
        defb    252
        defb    2
        defb    162
        defb    234
        defb    82
        defb    162
        defb    84
        defb    0
_tile160:
        defb    124
        defb    194
        defb    146
        defb    138
        defb    182
        defb    162
        defb    84
        defb    0
_tile161:
        defb    222
        defb    191
        defb    223
        defb    255
        defb    175
        defb    149
        defb    90
        defb    0
_tile162:
        defb    250
        defb    218
        defb    246
        defb    234
        defb    114
        defb    162
        defb    84
        defb    0
_tile163:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile164:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile165:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile166:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
_tile167:
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
        defb    0
